-- Módulo auth: identidad de acceso (usuario, sesión y verificaciones). No depende de ningún otro módulo.

-- ============ CATÁLOGOS ============
CREATE TABLE role (
    id   SMALLINT PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE user_status (
    id   SMALLINT PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE challenge_purpose (
    id           SMALLINT PRIMARY KEY,
    code         VARCHAR(30) NOT NULL UNIQUE,
    ttl_minutes  INTEGER NOT NULL CHECK (ttl_minutes > 0),
    max_attempts INTEGER NOT NULL CHECK (max_attempts > 0)
);

-- Los ids son fijos: el CHECK de customers depende del id de role
INSERT INTO role (id, code) VALUES (1, 'CUSTOMER'), (2, 'ADMIN');

INSERT INTO user_status (id, code) VALUES
    (1, 'ACTIVE'),
    (2, 'PENDING_VERIFICATION'),
    (3, 'INACTIVE'),
    (4, 'BLOCKED');

INSERT INTO challenge_purpose (id, code, ttl_minutes, max_attempts) VALUES
    (1, 'LOGIN',               5, 3),
    (2, 'EMAIL_CONFIRMATION', 30, 3),
    (3, 'PASSWORD_RESET',     15, 3);

-- ============ USUARIO ============
CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Siempre en minúsculas: Ana@x.com y ana@x.com son la misma identidad. El CHECK impide guardar
    -- otra cosa, sin importar por dónde entre el dato, y permite un UNIQUE normal.
    email               VARCHAR(254) NOT NULL UNIQUE,
    password_hash       VARCHAR(255) NOT NULL,
    password_changed_at TIMESTAMP NOT NULL,
    role_id             SMALLINT NOT NULL REFERENCES role (id),
    status_id           SMALLINT NOT NULL REFERENCES user_status (id),
    failed_attempts     INTEGER NOT NULL DEFAULT 0,
    last_login_at       TIMESTAMP,
    -- Último cambio real de estado: reloj de la inactividad junto con last_login_at
    status_changed_at   TIMESTAMP NOT NULL,
    created_at          TIMESTAMP NOT NULL,
    -- necesaria para la FK compuesta de los perfiles (customers)
    CONSTRAINT uk_users_id_role UNIQUE (id, role_id),
    CONSTRAINT ck_users_email_lowercase CHECK (email = lower(email))
);

CREATE INDEX idx_users_status_last_login ON users (status_id, last_login_at);

-- ============ SESIÓN ÚNICA Y VERIFICACIONES ============
CREATE TABLE auth_session (
    user_id    BIGINT PRIMARY KEY REFERENCES users (id),
    jti        VARCHAR(255) NOT NULL UNIQUE,
    issued_at  TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL
);

CREATE TABLE verification_challenge (
    id              UUID PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users (id),
    purpose_id      SMALLINT NOT NULL REFERENCES challenge_purpose (id),
    code_hash       VARCHAR(255) NOT NULL,
    expires_at      TIMESTAMP NOT NULL,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_challenge_user_purpose UNIQUE (user_id, purpose_id)
);
