CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    document_type VARCHAR(255) NOT NULL,
    document_number VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    last_login TIMESTAMP,
    current_token_id VARCHAR(255),
    two_factor_code VARCHAR(255),
    two_factor_code_expiration TIMESTAMP,
    two_factor_failed_attempts INTEGER NOT NULL DEFAULT 0,
    password_reset_token VARCHAR(255),
    password_reset_token_expiration TIMESTAMP,
    CONSTRAINT uk_customers_document_number UNIQUE (document_number),
    CONSTRAINT uk_customers_email UNIQUE (email),
    CONSTRAINT uk_customers_current_token_id UNIQUE (current_token_id)
);

CREATE INDEX idx_customers_status_last_login
    ON customers (status, last_login);

CREATE INDEX idx_customers_password_reset_token
    ON customers (password_reset_token);
