-- Módulo customer: datos personales del cliente. Depende de auth (users).

CREATE TABLE document_type (
    id   SMALLINT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO document_type (id, name) VALUES
    (1, 'Cédula de ciudadanía'),
    (2, 'Cédula de extranjería'),
    (3, 'Pasaporte');

CREATE TABLE customers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    role_id          SMALLINT NOT NULL DEFAULT 1,
    first_names      VARCHAR(100) NOT NULL,
    last_names       VARCHAR(100) NOT NULL,
    document_type_id SMALLINT NOT NULL REFERENCES document_type (id),
    document_number  VARCHAR(255) NOT NULL,
    phone            VARCHAR(16) NOT NULL,
    birth_date       DATE NOT NULL,
    created_at       TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP NOT NULL,
    CONSTRAINT uk_customers_user UNIQUE (user_id),
    CONSTRAINT uk_customers_document_number UNIQUE (document_number),
    CONSTRAINT ck_customers_role CHECK (role_id = 1),
    -- Junto con el CHECK impide que un usuario ADMIN tenga fila en customers
    CONSTRAINT fk_customers_user FOREIGN KEY (user_id, role_id) REFERENCES users (id, role_id)
);
