-- Separa seguridad (cuenta, sesión, verificaciones) de los datos del cliente.
-- Módulos cubiertos: auth y customer. Las filas ADMIN pasan a user_account; su perfil
-- se archiva en legacy_admin_profile hasta que exista el módulo staff.

-- ============ 1. CATÁLOGOS ============
CREATE TABLE role (
    id   SMALLINT PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE category (
    id   SMALLINT PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE status (
    id          SMALLINT PRIMARY KEY,
    category_id SMALLINT NOT NULL REFERENCES category (id),
    code        VARCHAR(30) NOT NULL,
    CONSTRAINT uk_status_category_code UNIQUE (category_id, code)
);

CREATE TABLE challenge_purpose (
    id           SMALLINT PRIMARY KEY,
    code         VARCHAR(30) NOT NULL UNIQUE,
    ttl_minutes  INTEGER NOT NULL CHECK (ttl_minutes > 0),
    max_attempts INTEGER NOT NULL CHECK (max_attempts > 0)
);

CREATE TABLE document_type (
    id   SMALLINT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO role (id, code) VALUES (1, 'CUSTOMER'), (2, 'ADMIN');

INSERT INTO category (id, code) VALUES (1, 'CUSTOMER'), (2, 'STAFF');

INSERT INTO status (id, category_id, code) VALUES
    (1, 1, 'ACTIVE'),
    (2, 1, 'PENDING_VERIFICATION'),
    (3, 1, 'INACTIVE'),
    (4, 1, 'BLOCKED'),
    (5, 2, 'ACTIVE'),
    (6, 2, 'PENDING_VERIFICATION'),
    (7, 2, 'BLOCKED'),
    (8, 2, 'TERMINATED');

INSERT INTO challenge_purpose (id, code, ttl_minutes, max_attempts) VALUES
    (1, 'LOGIN',               5, 3),
    (2, 'EMAIL_CONFIRMATION', 30, 3),
    (3, 'PASSWORD_RESET',     15, 3);

INSERT INTO document_type (id, name) VALUES
    (1, 'Cédula de ciudadanía'),
    (2, 'Cédula de extranjería'),
    (3, 'Pasaporte');

-- ============ 2. CUENTA, SESIÓN Y VERIFICACIONES ============
CREATE TABLE user_account (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(254) NOT NULL UNIQUE,
    password_hash       VARCHAR(255) NOT NULL,
    password_changed_at TIMESTAMP NOT NULL,
    role_id             SMALLINT NOT NULL REFERENCES role (id),
    status_id           SMALLINT NOT NULL REFERENCES status (id),
    failed_attempts     INTEGER NOT NULL DEFAULT 0,
    last_login_at       TIMESTAMP,
    created_at          TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_account_id_role UNIQUE (id, role_id)
);

CREATE INDEX idx_user_account_status_last_login ON user_account (status_id, last_login_at);

CREATE TABLE auth_session (
    user_account_id BIGINT PRIMARY KEY REFERENCES user_account (id),
    jti             VARCHAR(255) NOT NULL UNIQUE,
    issued_at       TIMESTAMP NOT NULL,
    expires_at      TIMESTAMP NOT NULL
);

CREATE TABLE verification_challenge (
    id              UUID PRIMARY KEY,
    user_account_id BIGINT NOT NULL REFERENCES user_account (id),
    purpose_id      SMALLINT NOT NULL REFERENCES challenge_purpose (id),
    code_hash       VARCHAR(255) NOT NULL,
    expires_at      TIMESTAMP NOT NULL,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_challenge_account_purpose UNIQUE (user_account_id, purpose_id)
);

-- ============ 3. VALIDACIONES PREVIAS (la migración falla si hay datos fuera del mapeo) ============
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM customers WHERE role NOT IN ('USER', 'ADMIN')) THEN
        RAISE EXCEPTION 'customers.role con valores fuera de USER/ADMIN: revisar a mano';
    END IF;
    IF EXISTS (SELECT 1 FROM customers WHERE status NOT IN ('ACTIVE', 'PENDING_VALIDATION', 'BLOCKED', 'INACTIVE')) THEN
        RAISE EXCEPTION 'customers.status con valores desconocidos: revisar a mano';
    END IF;
    IF EXISTS (SELECT 1 FROM customers WHERE role = 'USER' AND document_type NOT IN ('CC', 'CE', 'PASSPORT')) THEN
        RAISE EXCEPTION 'customers.document_type con valores fuera de CC/CE/PASSPORT: revisar a mano';
    END IF;
END $$;

-- ============ 4. UNA CUENTA POR CADA FILA DE customers ============
INSERT INTO user_account (email, password_hash, password_changed_at, role_id, status_id,
                          failed_attempts, last_login_at, created_at)
SELECT c.email,
       c.password_hash,
       now(),
       CASE c.role WHEN 'USER' THEN 1 WHEN 'ADMIN' THEN 2 END,
       CASE
           WHEN c.role = 'ADMIN' THEN
               CASE c.status
                   WHEN 'ACTIVE'             THEN 5
                   WHEN 'PENDING_VALIDATION' THEN 6
                   WHEN 'BLOCKED'            THEN 7
                   WHEN 'INACTIVE'           THEN 5  -- no existe para personal: revisión manual
               END
           ELSE
               CASE c.status
                   WHEN 'ACTIVE'             THEN 1
                   WHEN 'PENDING_VALIDATION' THEN 2
                   WHEN 'INACTIVE'           THEN 3
                   WHEN 'BLOCKED'            THEN 4
               END
       END,
       c.failed_attempts,
       c.last_login,
       now()
FROM customers c
ORDER BY c.id;

-- Perfil de los administradores: se conserva hasta que exista staff_member
CREATE TABLE legacy_admin_profile AS
SELECT ua.id AS user_account_id, c.name, c.document_type, c.document_number, c.phone, c.birth_date
FROM customers c
JOIN user_account ua ON ua.email = c.email
WHERE c.role = 'ADMIN';

-- ============ 5. customers: solo datos del cliente ============
ALTER TABLE customers
    ADD COLUMN user_account_id  BIGINT,
    ADD COLUMN role_id          SMALLINT NOT NULL DEFAULT 1,
    ADD COLUMN document_type_id SMALLINT,
    ADD COLUMN created_at       TIMESTAMP NOT NULL DEFAULT now(),
    ADD COLUMN updated_at       TIMESTAMP NOT NULL DEFAULT now();

DELETE FROM customers WHERE role = 'ADMIN';

UPDATE customers c
SET user_account_id  = ua.id,
    document_type_id = CASE c.document_type WHEN 'CC' THEN 1 WHEN 'CE' THEN 2 WHEN 'PASSPORT' THEN 3 END
FROM user_account ua
WHERE ua.email = c.email;

ALTER TABLE customers
    DROP COLUMN email,
    DROP COLUMN password_hash,
    DROP COLUMN role,
    DROP COLUMN status,
    DROP COLUMN failed_attempts,
    DROP COLUMN last_login,
    DROP COLUMN current_token_id,
    DROP COLUMN two_factor_code,
    DROP COLUMN two_factor_code_expiration,
    DROP COLUMN two_factor_failed_attempts,
    DROP COLUMN password_reset_token,
    DROP COLUMN password_reset_token_expiration,
    DROP COLUMN document_type;

ALTER TABLE customers
    ALTER COLUMN user_account_id SET NOT NULL,
    ALTER COLUMN document_type_id SET NOT NULL,
    ALTER COLUMN phone TYPE VARCHAR(30),
    ADD CONSTRAINT uk_customers_user_account UNIQUE (user_account_id),
    ADD CONSTRAINT ck_customers_role CHECK (role_id = 1),
    ADD CONSTRAINT fk_customers_document_type FOREIGN KEY (document_type_id) REFERENCES document_type (id),
    ADD CONSTRAINT fk_customers_account FOREIGN KEY (user_account_id, role_id)
        REFERENCES user_account (id, role_id);
